-- Supabase seed data (applied after migrations on `supabase db reset`).
--
-- The STARTER conflict matrix + PAO category defaults are seeded by migration
-- `…0013_seed_intelligence.sql` (so they deploy with `db push`), all
-- reviewed_by = NULL until clinical sign-off (BLOCKED: B-DERM-REVIEW, launch gate).
--
-- The ingredient/product CATALOG (CosIng ingredients + Open Beauty Facts products
-- + ingredient_tags) is intentionally NOT seeded yet:
--   BLOCKED: B-CATALOG-SEED — needs the verified CosIng bulk-download route and the
--     Open Beauty Facts daily dumps (via DuckDB; the live API is one call/scan).
--   License obligations: CosIng ("informative purpose, no legal value") and
--     Open Beauty Facts (ODbL — attribution + share-alike + contribute-back).
--
-- Leave empty until the catalog import pipeline runs (docs/02 §2).
