export const ANALYTICS_ALLOWED_EVENTS = [
  'account_created',
  'ask_consent_granted',
  'ask_consent_revoked',
  'ask_escalated_to_clinician',
  'ask_grounded_gated',
  'ask_opened',
  'ask_proactive_lead_shown',
  'ask_reported_problem',
  'ask_turn',
  'barcode_scanned',
  'barcode_decode_rejected',
  'barcode_decode_success',
  'catalog_barcode_lookup',
  'catalog_correction_reported',
  'catalog_lookup_no_match',
  'catalog_search',
  'cloud_backup_opted_in',
  'commerce_consent_declined',
  'commerce_consent_granted',
  'community_consent_granted',
  'comparison_viewed',
  'conflict_detected',
  'conflict_overridden',
  'conflict_resolution_chosen',
  'contextual_paywall_shown',
  'cycle_night_completed',
  'cycle_paused',
  'cycle_recovery_started',
  'cycle_resumed',
  'cycle_started',
  'cycle_variant_changed',
  'first_checkoff_completed',
  'first_photo_captured',
  'first_routine_created',
  'first_useful_insight',
  'health_consent_declined',
  'ingredient_parse_completed',
  'label_capture_photo_taken',
  'landing_viewed',
  'manage_subscription_opened',
  'night_skipped',
  'notification_prompt_denied',
  'notification_prompt_granted',
  'notification_prompt_shown',
  'onboarding_started',
  'opened_date_set',
  'paywall_dismissed',
  'paywall_shown',
  'personalization_shown',
  'phase7_deferred_surface_viewed',
  'phased_intro_overridden',
  'photo_capture_still_taken',
  'photo_baseline_added',
  'photo_captured',
  'preference_set',
  'product_add_started',
  'product_added',
  'product_scanned',
  'product_discarded',
  'product_finished',
  'purchase_completed',
  'question_submitted',
  'quiz_completed',
  'quiz_question_answered',
  'reaction_added',
  'recommendation_accepted',
  'recommendation_dismissed',
  'recommendation_expanded',
  'recommendation_shown',
  'reference_reset',
  'replenishment_nudge_shown',
  'replenishment_nudge_tapped',
  'restore_tapped',
  'review_prompt_attempted',
  'review_prompt_skipped',
  'review_prompt_unavailable',
  'reverse_trial_expired',
  'reverse_trial_started',
  'ramp_step_up_accepted',
  'ramp_step_up_offered',
  'routine_edited',
  'routine_checkoff_completed',
  'routine_created',
  'routine_plan_viewed',
  'screen_viewed',
  'scan_matched',
  'scan_no_match',
  'subscription_cancel_intent',
  'support_contact_failed',
  'support_contact_opened',
  'share_card_export_failed',
  'share_card_export_started',
  'share_card_export_succeeded',
  'share_card_exported',
  'share_link_created',
  'share_link_opened',
  'share_sheet_opened',
  'skin_note_viewed',
  'stack_viewed',
  'step_reordered',
  'streak_milestone_reached',
  'timeline_viewed',
  'transparency_viewed',
  'trend_consent_revoked',
  'trend_insights_opted_in',
  'trend_shown',
  'trial_started',
  'where_to_buy_clicked',
  'where_to_buy_link_failed',
  'why_tonight_viewed',
  'winback_converted',
  'winback_shown',
  'youre_set_shown',
] as const;

export type AnalyticsAllowedEventName = (typeof ANALYTICS_ALLOWED_EVENTS)[number];

export const ANALYTICS_ALLOWED_PROP_KEYS = [
  'action',
  'added_via',
  'answerKind',
  'barcode_type',
  'category',
  'context',
  'consented',
  'correction_type',
  'count',
  'campaign',
  'content',
  'creative_variant',
  'days',
  'feature',
  'flagged',
  'grounded',
  'is_opened',
  'kind',
  'landing_variant',
  'lookup_type',
  'matched',
  'medium',
  'milestone',
  'mode',
  'moment',
  'native_ocr_enabled',
  'on_device',
  'period_type',
  'reason',
  'reaction',
  'refused',
  'result',
  'screen_name',
  'share_id',
  'severity',
  'signal_source',
  'source',
  'streak',
  'store',
  'surface',
  'term',
  'type',
  'variant',
  'platform',
  'app_version',
  'build_number',
] as const;

export type AnalyticsAllowedPropKey = (typeof ANALYTICS_ALLOWED_PROP_KEYS)[number];

const allowedEvents = new Set<string>(ANALYTICS_ALLOWED_EVENTS);
const allowed = new Set<string>(ANALYTICS_ALLOWED_PROP_KEYS);

export function isAllowedAnalyticsEventName(event: string): event is AnalyticsAllowedEventName {
  return allowedEvents.has(event);
}

export function isAllowedAnalyticsPropKey(key: string): key is AnalyticsAllowedPropKey {
  return allowed.has(key);
}
